name: chess_snapshot_app
description: App for detecting chess positions from a photo of a real board.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image: ^4.1.7
  image_picker: ^1.0.7
  http: ^1.2.0
  chess_snapshot_chessboard:
    path: package/chess_snapshot_chessboard

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
