name: chess_snapshot_app
description: App for detecting chess positions from a photo of a real board.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.7
  image_picker: ^1.0.7
  http: ^1.2.0
  chess: ^0.8.1
  simple_chess_board: ^1.3.0
  persistent_bottom_nav_bar_v2: ^5.1.0
  font_awesome_flutter: ^10.7.0
  chess_snapshot_chessboard:
    path: package/chess_snapshot_chessboard
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
